name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.13"
              otp: "24.3.4.10"
          - pair:
              elixir: "1.17"
              otp: "27.0.1"
            lint: lint
            cover: cover
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: req_sandbox_test
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@main
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
          version-type: strict

      - uses: actions/cache@v4
        with:
          path: deps
          key: mix-deps-${{ hashFiles('**/mix.lock') }}

      - run: mix do deps.get --check-locked

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - run: mix test --warnings-as-errors
        if: ${{ ! matrix.cover }}

      - run: mix test --cover --warnings-as-errors
        if: ${{ matrix.cover }}

      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: cover
        if: ${{ matrix.cover }}
